name: deploy angular dashboard
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /etc/dmi-integrated-dashboards
          systemctl stop nginx
          pm2 stop 0
          echo "deployment complete"
