name: Deploy Integrated dashboards
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy Dashboards
    runs-on: ubuntu-latest
    steps:
    - name: updating and deploying app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /etc/dmi-integrated-dashboards
          sudo systemctl stop nginx
          sudo pm2 stop 0
          sudo rm -rf dist
          sudo git pull
          sudo find . -type f -exec sed -i 's/http:\/\/localhost:8080//g' {} +
          sudo ng build --configuration production
          sudo systemctl restart nginx
          sudo systemctl status nginx
          sudo pm2 reload 0
          echo "Deployment successful!"
