name: Deploy Angular-App
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: Sithi5/remote-ssh-commands-action@main
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_KEY }}
        port: ${{ secrets.PORT }}
    - name: Check Success status
      run: echo "Success"
            
