name: deploy angular dashboard
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: Sithi5/remote-ssh-commands-action@main
      with:
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.CICD_KEY }}
        SSH_HOST: ${{ secrets.HOST }}
        SSH_PORT: ${{ secrets.PORT }}
            
